### ISSUE TITLE
Typescript typings

### ISSUE THREAD

**Issue by WorldMaker** [nolanlawson/blob-util#26]
I wrote some Typescript typings for this library (a `.d.ts` file) and was curious if you would accept a PR to add them to the project? (It's easiest to work with typings when they are included directly in the npm package.)

**Comment by nolanlawson** [comment]
Sorry, but I prefer to keep typescript typings maintained in a separate project by the typescript community. Thanks for offering, though! :)

**Comment by nolanlawson** [comment]
To explain my reasoning: I don't really know typescript, and including them in the repo means that I essentially take responsibility for them when they break. I believe the TS community is best served by managing their own typings instead of expecting JS maintainers to understand TS and manage the typings. E.g. TypeScript tools could also just automatically install typings when they detect that you have `npm install`ed some project and the typings exist on DefinitelyTyped, typings, npm, wherever they're stored.

**Comment by atrauzzi** [comment]
@WorldMaker - Think you could publish those types to definitelytyped? 😄

**Comment by WorldMaker** [comment]
@atrauzzi: I may try again. All of my PRs lately seem to get stuck in PR purgatory there. It's way too big of a repository. I've had much more luck directly contributing to library repositories starting by asking like this issue. In the mean time, you can use typings to install from my "IndefinitivelyTyped" repository.

**Comment by atrauzzi** [comment]
Yeah, ideally packages would just include their own types, definitely typed is not offered as a premiere experience, but as a way to obtain a premiere experience.

TS is taking off in a big way lately, @nolanlawson - I urge you to reconsider! :)
