### ISSUE TITLE
Error with Angular 6.0.0

### ISSUE THREAD

**Issue by mbx2015** [nolanlawson/blob-util#42]
Uncaught ReferenceError: global is not defined
`var BlobBuilder = global.BlobBuilder
  || global.WebKitBlobBuilder
  || global.MSBlobBuilder
  || global.MozBlobBuilder;`

**Comment by nolanlawson** [comment]
Hmmm, I believe this can only happen if some code messes with the `global` or `window` object. Do you have a repro to show how this is happening?

Also this is a bug in [blob](https://github.com/webmodules/blob), not blob-util.

I'm inclined to close, because I am probably going to drop `blob` as a dependency anyway.

**Comment by nolanlawson** [comment]
This should be fixed in 2.0.0 now because I've dropped `blob` as a dependency
